const Game = {
Fonts : {
"Default Font":"m0_none",
"Flaming Red":"m2_vnsllq",
"Golden GOAT":"m1_nbkdsa",
"Gemtastic Green":"m3_ppvhrr",
"Pretty Prism":"m5_iyrewa",
"Seasoned Purple":"m4_lvnwos",
"Violet Visonary":"m4_lsobnj",
},
Characters : {
    "SirBotsalot":"a8zllcpdre",
    "BottyMcBotface":"a9egqgghed",
    "J5Alive":"a10aumsgjxn",
    "RononRobot":"a11gakyryfx",
    "BillyTheBot":"a12xirtrmzl",
    "Sammy":"a13",
    "Ollie":"a14",
    "Lily":"a15",
    "Aldo":"a16",
    "Mandy":"a17",
    "Mei":"a18",
    "Bacon":"a19",
    "Bumper":"a20",
    "Alan":"a21",
    "Steky Jr.":"a22",
    "Max Notstoppen":"a324_adfecnvv",
    "George Hustle":"a325_ayshgbwp",
    "Lando Floorit":"a326_lijhencb",
    "Brie-yan":"a332_chsehvfd",
    "Kato-Masuta":"a333_bhgqftdv",
    "Smash Racer":"a77_dujfkcvs",
    "Molly":"a32",
    "Cinnamon":"a41",
    "Flamin' Cinnamon":"a331_behgtafd",
    "Golden Molly":"a334_upkjkutj",
    "Jade Rabbit":"a78_fdlcjfny",
    "Dragon Rabbit":"a79_dufadjad",
    "McCaw":"a106_aclkjmuc",
    "George":"a42",
    "Toco":"a52_lwcfgaqu",
    "Grim":"a129_cvhbmnds",
    "Chip":"a359_dhsyhjnc",
    "SK Mugen Prime":"a353_cyfhaklw",
    "Jaden":"a237_ryxdjceb",
    "Kai":"a238_ndhazzkz",
},
Hats : {
    "noHat":"h0",
    "Saucepan":"h1",
    "Plunger":"h2",
    "Sheriff":"h3",
    "Afro":"h5",
    "Baseball Cap":"h7",
    "Kepi":"h8",
    "Old Hat":"h9",
    "Beret":"h12",
    "Chef":"h13",
    "Beanie":"h11",
    "botFace0":"h1000",
    "botFace1":"h1001",
    "botFace2":"h1002",
    "botFace3":"h1003",
    "botFace4":"h1004",
    "Conical":"h95",
    "Emperor":"h96",
    "Noodle Box":"h98",
    "Smooth Criminal":"h169_aycglmnv",
    "Texas":"h164_abolnmjh",
    "Uncle Sam":"h6",
    "Carnival Headdress":"h120_qodfgtxl",
},
Colors : {
    "Red and Blue":"c0",
    "Ninja Blue":"c7",
    "Bronze":"c13",
    "Mint Green":"c1",
    "Emerald Green":"c8",
    "Green White":"c6",
    "Light Pink Green":"c14",
    "Purple and Orange":"c3",
    "Pink":"c2",
    "Ruby Red":"c9",
    "Carrot Yellow":"c5",
    "McRacing":"c213_dtegkjcx",
    "Merc Silver":"c214_cgsfbgef",
    "Raging Bull":"c215_cyefdgcx",
    "SmashFest":"c140_fjcmsgll",
    "Dark Moon":"c141_idslcjdf",
    "Supernova":"c139_superdop",
    "Robot":"c1000",
    "USA":"c24",
    "Rio Carnival":"c133_riocrngf",
    "Cobra Gold":"c182_ezjlkvzw",
    "Jade Green":"c181_bcloajgy",
},
Celebrations : {
    "Confetti":"p0",
    "Super Powerz":"p00_villain",
    "Blossoms":"p3",
    "Bugle Call":"p7",
    "July 4th Fireworks":"p19qaerfdky",
    "Blasters":"p32_likjvgas",
    "Cannon Fire?!":"p93_hjgxsuty",
    "Turbo Thrusters: Engage!":"p111_qshdienm",
    "Snakes? Snakes!!":"p58_ihtvhito",
    "Soccer Ball":"p12_cjuhandt",
},
Wheels : {
    "Gray Slicks":"w0",
    "Gray Grooves":"w34_lgjtjdel",
    "The Mac' Racers":"w113_olpdhduj",
    "Merc Racers":"w112_sudtrebv",
    "Red Racers":"w111_chtegdok",
    "SmashFest Slicks":"w26_gjgjgotg",
    "Kart Krusher Wheel":"w00_villain",
    "Dark Moon Slicks":"w27_ajyeplmnf",
    "Supernova Slicks":"w24_blasfrde",
    "USA Slicks":"w11",
    "Rio Slicks":"w16_blaa",
    "Cobra Slicks":"w72_muaxtnjq",
    "Jade Slicks":"w71_htgmajtk",
},
Toppers : {
    "noTopper":"t0_none",
    "Red Flag":"t1_gsvh",
    "Blue Flag":"t2_vjmu",
    "Pink Flag":"t3_qfvj",
    "Green Flag":"t4_hima",
    "Nuke":"t5_gsvh",
    "Retro Decoy":"t6_jiqc",
    "Rubber Ducky":"t7_muom",
    "Coin":"t8_iqya",
    "Double Swords":"t9_leos",
    "Lightning Bolt":"t10_hvru",
    "Smash Racer":"t92_sgfmvjry",
    "Dare Devil":"t94_skcmnvhg",
    "Scarlet Smasher":"t95_dlcjgkop",
    "Rock'n Roller":"t93_djawcfys",
    "Checkered Flag":"t96_dolamchf",
    "Golden Moon":"t106_adkfigbv",
    "Eid Lantern":"t107_dyhstgbc",
    "Cricket World Cup":"t84_ajducm",
    "Cricket Bat":"t83_skvmng",
    "Cricket Ball":"t82_edbhj",
    "Noodlebox":"t97_adkfmnvh",
    "Smash Karts":"t52_loog",
    "SK Flag":"t69_masher",
    "Soccer Ball":"t31_foyt",
    "Pandeiro":"t32_azxf",
    "Carnival Mask":"t101_aikochlp",
    "Maracas":"t100_fkmchftg",
    "Jade Snek":"t362_zjeruzap",
    "Golden Snek":"t363_aebvxqfs",
    "Pumas":"t85_dkaucmnd",
    "The Blues":"t86_dcmvnfhr",
    "Red Fury":"t87_oifkalfk",
    "The Lions":"t88_gkdltcmg",
    "Stars and Stripes":"t89_fayedhck",
    "Samba":"t90_lstwmcdk",
    "World Cup Trophy":"t91_dkgyvmbn",
}}
